### ISSUE TITLE
Potisk - označení verze osazení

### ISSUE THREAD

**Issue by ChroustJan** [mlab-modules/TTLLVDS01#1]
Bylo by vhodné do potisku PCB přidat potisk, který by umožňoval identifikovat verzi osazení PCB.
TTL to LVDS nebo LVDS to TTL

**Comment by kaklik** [comment]
To tam je. 

![image](https://user-images.githubusercontent.com/1194177/161570568-fcffb7d5-d481-4879-9545-d822629a89cd.png)

Tady se škrtá, jestli je to vstup, nebo výstup. Stejný systém se osvědčil na modulech TTLPECL01.

**Comment by ChroustJan** [comment]
Dané nápisy jsem přehlédl.
